image: archlinux
oauth: pages.sr.ht/PAGES:RW
packages:
  - hut
  - rust
environment:
  site: carr.srht.site
tasks:
  - package: |
      cd www
      cargo run
      tar -C out -cvz . > ../site.tar.gz
  - upload: |
      hut pages publish -d $site site.tar.gz